springdoc:
  packages-to-scan: com.example.apidemo
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path:
    tags-sorter: alpha
    operations-sorter: alpha
    api-docs:
      path:
      groups:
        enabled: true
    cache:
      disabled: true
spring:
  datasource:
    url: jdbc:mysql://52.79.72.12:3306/apidemo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: builder
    password: 1234

  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true

logging:
  level:
    com.example: debug

jwt:
  secret: abcdefghijklmpipebuilderssecretkeyhellosanghunhongchulshellobuildersgoodgoodwowfsdfsdfsdfsdkjlkjflkslgwlegbjlwoeiflkxoczxkkweijflkjw