springdoc:
  packages-to-scan: com.example.apidemo
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path:
    tags-sorter: alpha
    operations-sorter: alpha
    api-docs:
      path:
      groups:
        enabled: true
    cache:
      disabled: true
spring:
############# mysql datasorce  ###############
#  datasource:
#    url: jdbc:mysql://52.79.72.12:3306/apidemo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: builder
#    password: 1234
  #############################################

############### h2 datasorce #################
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/apidemo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  #############################################

  ############### mysql jpa #################

#  jpa:
#    database: mysql
#    generate-ddl: true
#    show-sql: true

  #############################################

  ############### h2 jpa #################
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #############################################

logging:
  level:
    com.example: debug

jwt:
  secret: abcdefghijklmpipebuilderssecretkeyhellosanghunhongchulshellobuildersgoodgoodwowfsdfsdfsdfsdkjlkjflkslgwlegbjlwoeiflkxoczxkkweijflkjw